name: Build & Publish RustDesk Binaries

# Trigger on any pushed tag matching v*
on:
  push:
    tags: ["v*"]

# Default shell
defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-${{ matrix.target }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: windows-latest
            target: x86_64-pc-windows-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache Cargo git index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-git-

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          profile: minimal
          cache: "cargo"

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/rustdesk*

  release:
    name: Create & Publish Release
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: release-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # needed for the commit-back step

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          name: rustdesk-*

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload binaries to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            target/x86_64-unknown-linux-gnu/release/rustdesk
            target/aarch64-unknown-linux-gnu/release/rustdesk
            target/x86_64-pc-windows-gnu/release/rustdesk.exe
            target/x86_64-apple-darwin/release/rustdesk
            target/aarch64-apple-darwin/release/rustdesk
          asset_name: |
            rustdesk-linux-x64
            rustdesk-linux-arm64
            rustdesk-windows-x64.exe
            rustdesk-macos-x64
            rustdesk-macos-arm64
          asset_content_type: application/octet-stream

      - name: Generate DOWNLOADS.md
        run: |
          cat > DOWNLOADS.md <<EOF
          # RustDesk ${{ github.ref_name }} Downloads

          | Platform           | Link |
          |--------------------|------|
          | Linux x86_64       | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/rustdesk-linux-x64) |
          | Linux ARM64        | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/rustdesk-linux-arm64) |
          | Windows x86_64     | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/rustdesk-windows-x64.exe) |
          | macOS x86_64       | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/rustdesk-macos-x64) |
          | macOS ARM64 (M1)   | [Download](https://github.com/${{ github.repository }}/releases/download/${{ github.ref_name }}/rustdesk-macos-arm64) |
          EOF

      - name: Commit DOWNLOADS.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📦 Update download table for ${{ github.ref_name }}"
          file_pattern: DOWNLOADS.md
